DROP DATABASE IF EXISTS catalog_db;
CREATE DATABASE catalog_db;

USE catalog_db;

CREATE TABLE departments (
  id INT NOT NULL,
  date_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE roles (
  role_id INT NOT NULL,
  department VARCHAR(30) NOT NULL,
  salary INT NOT NULL,
  date_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE employees (
  id INT NOT NULL,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  job_title VARCHAR(30) NOT NULL,
  department VARCHAR(30) NOT NULL,
  salaries INT NOT NULL,
  manager VARCHAR(30) NOT NULL,
  date_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);